
package weaver.hrm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HrmServicePortType", targetNamespace = "http://localhost/services/HrmService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HrmServicePortType {


    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns boolean
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.changeUserPassword")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "changeUserPassword", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.ChangeUserPassword")
    @ResponseWrapper(localName = "changeUserPasswordResponse", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.ChangeUserPasswordResponse")
    public boolean changeUserPassword(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        String in2);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmJobTitleInfoXML")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmJobTitleInfoXML", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.GetHrmJobTitleInfoXML")
    @ResponseWrapper(localName = "getHrmJobTitleInfoXMLResponse", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.GetHrmJobTitleInfoXMLResponse")
    public String getHrmJobTitleInfoXML(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        String in2);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmDepartmentInfoXML")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmDepartmentInfoXML", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.GetHrmDepartmentInfoXML")
    @ResponseWrapper(localName = "getHrmDepartmentInfoXMLResponse", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.GetHrmDepartmentInfoXMLResponse")
    public String getHrmDepartmentInfoXML(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SynSubCompany", action = "urn:weaver.hrm.webservice.HrmService.SynSubCompany")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "SynSubCompany", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.SynSubCompany")
    @ResponseWrapper(localName = "SynSubCompanyResponse", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.SynSubCompanyResponse")
    public String synSubCompany(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns weaver.hrm.ArrayOfJobTitleBean
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmJobTitleInfo")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmJobTitleInfo", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.GetHrmJobTitleInfo")
    @ResponseWrapper(localName = "getHrmJobTitleInfoResponse", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.GetHrmJobTitleInfoResponse")
    public ArrayOfJobTitleBean getHrmJobTitleInfo(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        String in2);

    /**
     * 
     * @param in0
     * @return
     *     returns weaver.hrm.ArrayOfSubCompanyBean
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmSubcompanyInfo")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmSubcompanyInfo", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.GetHrmSubcompanyInfo")
    @ResponseWrapper(localName = "getHrmSubcompanyInfoResponse", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.GetHrmSubcompanyInfoResponse")
    public ArrayOfSubCompanyBean getHrmSubcompanyInfo(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SynDepartment", action = "urn:weaver.hrm.webservice.HrmService.SynDepartment")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "SynDepartment", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.SynDepartment")
    @ResponseWrapper(localName = "SynDepartmentResponse", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.SynDepartmentResponse")
    public String synDepartment(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1);

    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns weaver.hrm.ArrayOfUserBean
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmUserInfo")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmUserInfo", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.GetHrmUserInfo")
    @ResponseWrapper(localName = "getHrmUserInfoResponse", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.GetHrmUserInfoResponse")
    public ArrayOfUserBean getHrmUserInfo(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/HrmService")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost/services/HrmService")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://localhost/services/HrmService")
        String in5);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns boolean
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.checkUser")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "checkUser", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.CheckUser")
    @ResponseWrapper(localName = "checkUserResponse", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.CheckUserResponse")
    public boolean checkUser(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        String in2);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SynHrmResource", action = "urn:weaver.hrm.webservice.HrmService.SynHrmResource")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "SynHrmResource", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.SynHrmResource")
    @ResponseWrapper(localName = "SynHrmResourceResponse", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.SynHrmResourceResponse")
    public String synHrmResource(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns weaver.hrm.ArrayOfDepartmentBean
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmDepartmentInfo")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmDepartmentInfo", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.GetHrmDepartmentInfo")
    @ResponseWrapper(localName = "getHrmDepartmentInfoResponse", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.GetHrmDepartmentInfoResponse")
    public ArrayOfDepartmentBean getHrmDepartmentInfo(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SynJobtitle", action = "urn:weaver.hrm.webservice.HrmService.SynJobtitle")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "SynJobtitle", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.SynJobtitle")
    @ResponseWrapper(localName = "SynJobtitleResponse", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.SynJobtitleResponse")
    public String synJobtitle(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmSubcompanyInfoXML")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmSubcompanyInfoXML", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.GetHrmSubcompanyInfoXML")
    @ResponseWrapper(localName = "getHrmSubcompanyInfoXMLResponse", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.GetHrmSubcompanyInfoXMLResponse")
    public String getHrmSubcompanyInfoXML(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0);

    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.hrm.webservice.HrmService.getHrmUserInfoXML")
    @WebResult(name = "out", targetNamespace = "http://localhost/services/HrmService")
    @RequestWrapper(localName = "getHrmUserInfoXML", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.GetHrmUserInfoXML")
    @ResponseWrapper(localName = "getHrmUserInfoXMLResponse", targetNamespace = "http://localhost/services/HrmService", className = "weaver.hrm.GetHrmUserInfoXMLResponse")
    public String getHrmUserInfoXML(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/HrmService")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/HrmService")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/HrmService")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/HrmService")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost/services/HrmService")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://localhost/services/HrmService")
        String in5);

}
