
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebArchivesFor10", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.188.222:8888/Services/WebArchivesFor10.asmx?wsdl")
public class WebArchivesFor10
    extends Service
{

    private final static URL WEBARCHIVESFOR10_WSDL_LOCATION;
    private final static WebServiceException WEBARCHIVESFOR10_EXCEPTION;
    private final static QName WEBARCHIVESFOR10_QNAME = new QName("http://tempuri.org/", "WebArchivesFor10");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.188.222:8888/Services/WebArchivesFor10.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBARCHIVESFOR10_WSDL_LOCATION = url;
        WEBARCHIVESFOR10_EXCEPTION = e;
    }

    public WebArchivesFor10() {
        super(__getWsdlLocation(), WEBARCHIVESFOR10_QNAME);
    }

    public WebArchivesFor10(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBARCHIVESFOR10_QNAME, features);
    }

    public WebArchivesFor10(URL wsdlLocation) {
        super(wsdlLocation, WEBARCHIVESFOR10_QNAME);
    }

    public WebArchivesFor10(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBARCHIVESFOR10_QNAME, features);
    }

    public WebArchivesFor10(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebArchivesFor10(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebArchivesFor10Soap
     */
    @WebEndpoint(name = "WebArchivesFor10Soap")
    public WebArchivesFor10Soap getWebArchivesFor10Soap() {
        return super.getPort(new QName("http://tempuri.org/", "WebArchivesFor10Soap"), WebArchivesFor10Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebArchivesFor10Soap
     */
    @WebEndpoint(name = "WebArchivesFor10Soap")
    public WebArchivesFor10Soap getWebArchivesFor10Soap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WebArchivesFor10Soap"), WebArchivesFor10Soap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBARCHIVESFOR10_EXCEPTION!= null) {
            throw WEBARCHIVESFOR10_EXCEPTION;
        }
        return WEBARCHIVESFOR10_WSDL_LOCATION;
    }

}
