
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebArchivesFor10Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebArchivesFor10Soap {


    /**
     * 
     * @param result
     * @param fileID
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SubmitDoucmentResult", action = "http://tempuri.org/SubmitDoucmentResult")
    @WebResult(name = "SubmitDoucmentResultResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SubmitDoucmentResult", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SubmitDoucmentResult")
    @ResponseWrapper(localName = "SubmitDoucmentResultResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SubmitDoucmentResultResponse")
    public boolean submitDoucmentResult(
        @WebParam(name = "fileID", targetNamespace = "http://tempuri.org/")
        String fileID,
        @WebParam(name = "result", targetNamespace = "http://tempuri.org/")
        boolean result);

}
