
package weaver.flow;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WorkflowServicePortType", targetNamespace = "webservices.services.weaver.com.cn")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WorkflowServicePortType {


    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.forward2WorkflowRequest")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "forward2WorkflowRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.Forward2WorkflowRequest")
    @ResponseWrapper(localName = "forward2WorkflowRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.Forward2WorkflowRequestResponse")
    public String forward2WorkflowRequest(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        String in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        String in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        String in4);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns weaver.flow.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getAllWorkflowRequestList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getAllWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetAllWorkflowRequestList")
    @ResponseWrapper(localName = "getAllWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetAllWorkflowRequestListResponse")
    public ArrayOfWorkflowRequestInfo getAllWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4);

    /**
     * 
     * @param in2
     * @param in1
     * @param in0
     * @return
     *     returns weaver.flow.WorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getWorkflowRequest")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getWorkflowRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetWorkflowRequest")
    @ResponseWrapper(localName = "getWorkflowRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetWorkflowRequestResponse")
    public WorkflowRequestInfo getWorkflowRequest(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns weaver.flow.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getHendledWorkflowRequestList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getHendledWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetHendledWorkflowRequestList")
    @ResponseWrapper(localName = "getHendledWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetHendledWorkflowRequestListResponse")
    public ArrayOfWorkflowRequestInfo getHendledWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns weaver.flow.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getToDoWorkflowRequestList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getToDoWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetToDoWorkflowRequestList")
    @ResponseWrapper(localName = "getToDoWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetToDoWorkflowRequestListResponse")
    public ArrayOfWorkflowRequestInfo getToDoWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4);

    /**
     * 
     * @param in2
     * @param in1
     * @param in3
     * @param in0
     * @return
     *     returns weaver.flow.WorkflowRequestInfo
     */
    @WebMethod(operationName = "getWorkflowRequest4split", action = "urn:weaver.workflow.webservices.WorkflowService.getWorkflowRequest4split")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getWorkflowRequest4split", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetWorkflowRequest4Split")
    @ResponseWrapper(localName = "getWorkflowRequest4splitResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetWorkflowRequest4SplitResponse")
    public WorkflowRequestInfo getWorkflowRequest4Split(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.submitWorkflowRequest")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "submitWorkflowRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.SubmitWorkflowRequest")
    @ResponseWrapper(localName = "submitWorkflowRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.SubmitWorkflowRequestResponse")
    public String submitWorkflowRequest(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        WorkflowRequestInfo in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        String in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        String in4);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getHendledWorkflowRequestCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getHendledWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetHendledWorkflowRequestCount")
    @ResponseWrapper(localName = "getHendledWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetHendledWorkflowRequestCountResponse")
    public int getHendledWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getLeaveDays")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getLeaveDays", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetLeaveDays")
    @ResponseWrapper(localName = "getLeaveDaysResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetLeaveDaysResponse")
    public String getLeaveDays(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        String in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        String in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        String in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        String in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        String in4);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @return
     *     returns weaver.flow.ArrayOfWorkflowBaseInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getCreateWorkflowList", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetCreateWorkflowList")
    @ResponseWrapper(localName = "getCreateWorkflowListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetCreateWorkflowListResponse")
    public ArrayOfWorkflowBaseInfo getCreateWorkflowList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        int in4,
        @WebParam(name = "in5", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in5);

    /**
     * 
     * @param in2
     * @param in1
     * @param in0
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getCreateWorkflowCount", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetCreateWorkflowCount")
    @ResponseWrapper(localName = "getCreateWorkflowCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetCreateWorkflowCountResponse")
    public int getCreateWorkflowCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in2);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getProcessedWorkflowRequestCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getProcessedWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetProcessedWorkflowRequestCount")
    @ResponseWrapper(localName = "getProcessedWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetProcessedWorkflowRequestCountResponse")
    public int getProcessedWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.forwardWorkflowRequest")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "forwardWorkflowRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.ForwardWorkflowRequest")
    @ResponseWrapper(localName = "forwardWorkflowRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.ForwardWorkflowRequestResponse")
    public String forwardWorkflowRequest(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        String in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        String in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        String in4);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.doCreateWorkflowRequest")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "doCreateWorkflowRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.DoCreateWorkflowRequest")
    @ResponseWrapper(localName = "doCreateWorkflowRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.DoCreateWorkflowRequestResponse")
    public String doCreateWorkflowRequest(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        WorkflowRequestInfo in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.doForceOver")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "doForceOver", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.DoForceOver")
    @ResponseWrapper(localName = "doForceOverResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.DoForceOverResponse")
    public String doForceOver(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCCWorkflowRequestCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getCCWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetCCWorkflowRequestCount")
    @ResponseWrapper(localName = "getCCWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetCCWorkflowRequestCountResponse")
    public int getCCWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns weaver.flow.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getProcessedWorkflowRequestList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getProcessedWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetProcessedWorkflowRequestList")
    @ResponseWrapper(localName = "getProcessedWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetProcessedWorkflowRequestListResponse")
    public ArrayOfWorkflowRequestInfo getProcessedWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getAllWorkflowRequestCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getAllWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetAllWorkflowRequestCount")
    @ResponseWrapper(localName = "getAllWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetAllWorkflowRequestCountResponse")
    public int getAllWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns weaver.flow.WorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowRequestInfo")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getCreateWorkflowRequestInfo", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetCreateWorkflowRequestInfo")
    @ResponseWrapper(localName = "getCreateWorkflowRequestInfoResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetCreateWorkflowRequestInfoResponse")
    public WorkflowRequestInfo getCreateWorkflowRequestInfo(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns weaver.flow.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getMyWorkflowRequestList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getMyWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetMyWorkflowRequestList")
    @ResponseWrapper(localName = "getMyWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetMyWorkflowRequestListResponse")
    public ArrayOfWorkflowRequestInfo getMyWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns weaver.flow.ArrayOfWorkflowBaseInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowTypeList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getCreateWorkflowTypeList", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetCreateWorkflowTypeList")
    @ResponseWrapper(localName = "getCreateWorkflowTypeListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetCreateWorkflowTypeListResponse")
    public ArrayOfWorkflowBaseInfo getCreateWorkflowTypeList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getMyWorkflowRequestCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getMyWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetMyWorkflowRequestCount")
    @ResponseWrapper(localName = "getMyWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetMyWorkflowRequestCountResponse")
    public int getMyWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns weaver.flow.ArrayOfString
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getWorkflowNewFlag")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getWorkflowNewFlag", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetWorkflowNewFlag")
    @ResponseWrapper(localName = "getWorkflowNewFlagResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetWorkflowNewFlagResponse")
    public ArrayOfString getWorkflowNewFlag(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        String in1);

    /**
     * 
     * @param in1
     * @param in0
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.writeWorkflowReadFlag")
    @RequestWrapper(localName = "writeWorkflowReadFlag", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.WriteWorkflowReadFlag")
    @ResponseWrapper(localName = "writeWorkflowReadFlagResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.WriteWorkflowReadFlagResponse")
    public void writeWorkflowReadFlag(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        String in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        String in1);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getToDoWorkflowRequestCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getToDoWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetToDoWorkflowRequestCount")
    @ResponseWrapper(localName = "getToDoWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetToDoWorkflowRequestCountResponse")
    public int getToDoWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1);

    /**
     * 
     * @param in2
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.givingOpinions")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "givingOpinions", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GivingOpinions")
    @ResponseWrapper(localName = "givingOpinionsResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GivingOpinionsResponse")
    public String givingOpinions(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        String in2);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowTypeCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getCreateWorkflowTypeCount", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetCreateWorkflowTypeCount")
    @ResponseWrapper(localName = "getCreateWorkflowTypeCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetCreateWorkflowTypeCountResponse")
    public int getCreateWorkflowTypeCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns weaver.flow.ArrayOfWorkflowRequestLog
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getWorkflowRequestLogs")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getWorkflowRequestLogs", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetWorkflowRequestLogs")
    @ResponseWrapper(localName = "getWorkflowRequestLogsResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetWorkflowRequestLogsResponse")
    public ArrayOfWorkflowRequestLog getWorkflowRequestLogs(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        String in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        String in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        int in4);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns boolean
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.deleteRequest")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "deleteRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.DeleteRequest")
    @ResponseWrapper(localName = "deleteRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.DeleteRequestResponse")
    public boolean deleteRequest(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns weaver.flow.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCCWorkflowRequestList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getCCWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetCCWorkflowRequestList")
    @ResponseWrapper(localName = "getCCWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetCCWorkflowRequestListResponse")
    public ArrayOfWorkflowRequestInfo getCCWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getUserid")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getUserId", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetUserId")
    @ResponseWrapper(localName = "getUserIdResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "weaver.flow.GetUserIdResponse")
    public String getUserId(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        String in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        String in1);

}
