//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 11:22:44 AM CST 
//


package com.seeyou.pojo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataProperty">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DataPojo" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="DataProperty" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="DataValue" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="isnull" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="propertyname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="valuetype" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                     &lt;attribute name="isnull" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="valuecount" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="isnull" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="propertyname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="valuetype" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="isnull" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}short" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="isnull" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valuecount" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataProperty"
})
@XmlRootElement(name = "DataPojo")
public class DataPojo {

    @XmlElement(name = "DataProperty", required = true)
    protected DataPojo.DataProperty dataProperty;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "version")
    protected Byte version;
    @XmlAttribute(name = "isnull")
    protected String isnull;
    @XmlAttribute(name = "valuecount")
    protected Byte valuecount;

    /**
     * Gets the value of the dataProperty property.
     * 
     * @return
     *     possible object is
     *     {@link DataPojo.DataProperty }
     *     
     */
    public DataPojo.DataProperty getDataProperty() {
        return dataProperty;
    }

    /**
     * Sets the value of the dataProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataPojo.DataProperty }
     *     
     */
    public void setDataProperty(DataPojo.DataProperty value) {
        this.dataProperty = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setVersion(Byte value) {
        this.version = value;
    }

    /**
     * Gets the value of the isnull property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsnull() {
        return isnull;
    }

    /**
     * Sets the value of the isnull property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsnull(String value) {
        this.isnull = value;
    }

    /**
     * Gets the value of the valuecount property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getValuecount() {
        return valuecount;
    }

    /**
     * Sets the value of the valuecount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setValuecount(Byte value) {
        this.valuecount = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DataPojo" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="DataProperty" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="DataValue" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="isnull" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="propertyname" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="valuetype" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                           &lt;attribute name="isnull" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="valuecount" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="isnull" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="propertyname" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="valuetype" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="isnull" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}short" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataPojo"
    })
    public static class DataProperty {

        @XmlElement(name = "DataPojo")
        protected List<DataPojo.DataProperty.DataPojo1> dataPojo;
        @XmlAttribute(name = "propertyname")
        protected String propertyname;
        @XmlAttribute(name = "valuetype")
        protected Byte valuetype;
        @XmlAttribute(name = "isnull")
        protected String isnull;
        @XmlAttribute(name = "length")
        protected Short length;

        /**
         * Gets the value of the dataPojo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dataPojo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDataPojo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DataPojo.DataProperty.DataPojo }
         * 
         * 
         */
        public List<DataPojo.DataProperty.DataPojo1> getDataPojo() {
            if (dataPojo == null) {
                dataPojo = new ArrayList<DataPojo.DataProperty.DataPojo1>();
            }
            return this.dataPojo;
        }

        /**
         * Gets the value of the propertyname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPropertyname() {
            return propertyname;
        }

        /**
         * Sets the value of the propertyname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPropertyname(String value) {
            this.propertyname = value;
        }

        /**
         * Gets the value of the valuetype property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getValuetype() {
            return valuetype;
        }

        /**
         * Sets the value of the valuetype property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setValuetype(Byte value) {
            this.valuetype = value;
        }

        /**
         * Gets the value of the isnull property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsnull() {
            return isnull;
        }

        /**
         * Sets the value of the isnull property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsnull(String value) {
            this.isnull = value;
        }

        /**
         * Gets the value of the length property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getLength() {
            return length;
        }

        /**
         * Sets the value of the length property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setLength(Short value) {
            this.length = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="DataProperty" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="DataValue" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="isnull" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="propertyname" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="valuetype" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                 &lt;attribute name="isnull" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="valuecount" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="isnull" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dataProperty"
        })
        public static class DataPojo1 {

            @XmlElement(name = "DataProperty")
            protected List<DataPojo.DataProperty.DataPojo1.DataProperty1> dataProperty;
            @XmlAttribute(name = "type")
            protected String type;
            @XmlAttribute(name = "version")
            protected Byte version;
            @XmlAttribute(name = "valuecount")
            protected Byte valuecount;
            @XmlAttribute(name = "isnull")
            protected String isnull;

            /**
             * Gets the value of the dataProperty property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the dataProperty property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDataProperty().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DataPojo.DataProperty.DataPojo.DataProperty }
             * 
             * 
             */
            public List<DataPojo.DataProperty.DataPojo1.DataProperty1> getDataProperty() {
                if (dataProperty == null) {
                    dataProperty = new ArrayList<DataPojo.DataProperty.DataPojo1.DataProperty1>();
                }
                return this.dataProperty;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the version property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getVersion() {
                return version;
            }

            /**
             * Sets the value of the version property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setVersion(Byte value) {
                this.version = value;
            }

            /**
             * Gets the value of the valuecount property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getValuecount() {
                return valuecount;
            }

            /**
             * Sets the value of the valuecount property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setValuecount(Byte value) {
                this.valuecount = value;
            }

            /**
             * Gets the value of the isnull property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsnull() {
                return isnull;
            }

            /**
             * Sets the value of the isnull property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsnull(String value) {
                this.isnull = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="DataValue" minOccurs="0">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="isnull" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="propertyname" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="valuetype" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *       &lt;attribute name="isnull" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "content"
            })
            public static class DataProperty1 {

                @XmlElementRef(name = "DataValue", type = JAXBElement.class, required = false)
                @XmlMixed
                protected List<Serializable> content;
                @XmlAttribute(name = "propertyname")
                protected String propertyname;
                @XmlAttribute(name = "valuetype")
                protected Byte valuetype;
                @XmlAttribute(name = "isnull")
                protected String isnull;
                @XmlAttribute(name = "length")
                protected Byte length;
                @XmlAttribute(name = "value")
                protected String value;

                /**
                 * Gets the value of the content property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the content property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getContent().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * {@link JAXBElement }{@code <}{@link DataPojo.DataProperty.DataPojo.DataProperty.DataValue }{@code >}
                 * 
                 * 
                 */
                public List<Serializable> getContent() {
                    if (content == null) {
                        content = new ArrayList<Serializable>();
                    }
                    return this.content;
                }

                /**
                 * Gets the value of the propertyname property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPropertyname() {
                    return propertyname;
                }

                /**
                 * Sets the value of the propertyname property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPropertyname(String value) {
                    this.propertyname = value;
                }

                /**
                 * Gets the value of the valuetype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getValuetype() {
                    return valuetype;
                }

                /**
                 * Sets the value of the valuetype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setValuetype(Byte value) {
                    this.valuetype = value;
                }

                /**
                 * Gets the value of the isnull property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIsnull() {
                    return isnull;
                }

                /**
                 * Sets the value of the isnull property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIsnull(String value) {
                    this.isnull = value;
                }

                /**
                 * Gets the value of the length property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getLength() {
                    return length;
                }

                /**
                 * Sets the value of the length property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setLength(Byte value) {
                    this.length = value;
                }

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="isnull" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class DataValue {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "isnull")
                    protected String isnull;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the isnull property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getIsnull() {
                        return isnull;
                    }

                    /**
                     * Sets the value of the isnull property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setIsnull(String value) {
                        this.isnull = value;
                    }

                }

            }

        }

    }

}
