//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 11:22:44 AM CST 
//


package com.seeyou.pojo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.seeyou.pojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataPojoDataPropertyDataPojoDataPropertyDataValue_QNAME = new QName("", "DataValue");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.seeyou.pojo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link com.seeyou.pojo.DataPojo }
     * 
     */
    public com.seeyou.pojo.DataPojo createDataPojo() {
        return new com.seeyou.pojo.DataPojo();
    }

    /**
     * Create an instance of {@link com.seeyou.pojo.DataPojo.DataProperty }
     * 
     */
    public com.seeyou.pojo.DataPojo.DataProperty createDataPojoDataProperty() {
        return new com.seeyou.pojo.DataPojo.DataProperty();
    }

    /**
     * Create an instance of {@link com.seeyou.pojo.DataPojo.DataProperty.DataPojo1 }
     * 
     */
    public com.seeyou.pojo.DataPojo.DataProperty.DataPojo1 createDataPojoDataPropertyDataPojo() {
        return new com.seeyou.pojo.DataPojo.DataProperty.DataPojo1();
    }

    /**
     * Create an instance of {@link com.seeyou.pojo.DataPojo.DataProperty.DataPojo1.DataProperty1 }
     * 
     */
    public com.seeyou.pojo.DataPojo.DataProperty.DataPojo1.DataProperty1 createDataPojoDataPropertyDataPojoDataProperty() {
        return new com.seeyou.pojo.DataPojo.DataProperty.DataPojo1.DataProperty1();
    }

    /**
     * Create an instance of {@link com.seeyou.pojo.DataPojo.DataProperty.DataPojo1.DataProperty1.DataValue }
     * 
     */
    public com.seeyou.pojo.DataPojo.DataProperty.DataPojo1.DataProperty1.DataValue createDataPojoDataPropertyDataPojoDataPropertyDataValue() {
        return new com.seeyou.pojo.DataPojo.DataProperty.DataPojo1.DataProperty1.DataValue();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.seeyou.pojo.DataPojo.DataProperty.DataPojo1.DataProperty1.DataValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataValue", scope = com.seeyou.pojo.DataPojo.DataProperty.DataPojo1.DataProperty1.class)
    public JAXBElement<com.seeyou.pojo.DataPojo.DataProperty.DataPojo1.DataProperty1.DataValue> createDataPojoDataPropertyDataPojoDataPropertyDataValue(com.seeyou.pojo.DataPojo.DataProperty.DataPojo1.DataProperty1.DataValue value) {
        return new JAXBElement<com.seeyou.pojo.DataPojo.DataProperty.DataPojo1.DataProperty1.DataValue>(_DataPojoDataPropertyDataPojoDataPropertyDataValue_QNAME, com.seeyou.pojo.DataPojo.DataProperty.DataPojo1.DataProperty1.DataValue.class, com.seeyou.pojo.DataPojo.DataProperty.DataPojo1.DataProperty1.class, value);
    }

}
