
package weaver.hrm.sso;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZKHrmService", targetNamespace = "webservices.hrm.alex.com.cn", wsdlLocation = "http://183.64.63.155:83/services/ZKHrmService?wsdl")
public class ZKHrmService
    extends Service
{

    private final static URL ZKHRMSERVICE_WSDL_LOCATION;
    private final static WebServiceException ZKHRMSERVICE_EXCEPTION;
    private final static QName ZKHRMSERVICE_QNAME = new QName("webservices.hrm.alex.com.cn", "ZKHrmService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://183.64.63.155:83/services/ZKHrmService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZKHRMSERVICE_WSDL_LOCATION = url;
        ZKHRMSERVICE_EXCEPTION = e;
    }

    public ZKHrmService() {
        super(__getWsdlLocation(), ZKHRMSERVICE_QNAME);
    }

    public ZKHrmService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZKHRMSERVICE_QNAME, features);
    }

    public ZKHrmService(URL wsdlLocation) {
        super(wsdlLocation, ZKHRMSERVICE_QNAME);
    }

    public ZKHrmService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZKHRMSERVICE_QNAME, features);
    }

    public ZKHrmService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZKHrmService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZKHrmServicePortType
     */
    @WebEndpoint(name = "ZKHrmServiceHttpPort")
    public ZKHrmServicePortType getZKHrmServiceHttpPort() {
        return super.getPort(new QName("webservices.hrm.alex.com.cn", "ZKHrmServiceHttpPort"), ZKHrmServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZKHrmServicePortType
     */
    @WebEndpoint(name = "ZKHrmServiceHttpPort")
    public ZKHrmServicePortType getZKHrmServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("webservices.hrm.alex.com.cn", "ZKHrmServiceHttpPort"), ZKHrmServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZKHRMSERVICE_EXCEPTION!= null) {
            throw ZKHRMSERVICE_EXCEPTION;
        }
        return ZKHRMSERVICE_WSDL_LOCATION;
    }

}
