//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.21 at 08:57:39 PM CST 
//


package weaver.hrm.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DepartmentBean" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="departmentid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fullname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="subcompanyid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="supdepartmentid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="showorder" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lastChangdate" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="canceled" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "departmentBean"
})
@XmlRootElement(name = "DepartmentBean-array")
public class DepartmentBeanArray {

    @XmlElement(name = "DepartmentBean")
    protected List<DepartmentBeanArray.DepartmentBean> departmentBean;

    /**
     * Gets the value of the departmentBean property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the departmentBean property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDepartmentBean().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DepartmentBeanArray.DepartmentBean }
     * 
     * 
     */
    public List<DepartmentBeanArray.DepartmentBean> getDepartmentBean() {
        if (departmentBean == null) {
            departmentBean = new ArrayList<DepartmentBeanArray.DepartmentBean>();
        }
        return this.departmentBean;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="departmentid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fullname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="subcompanyid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="supdepartmentid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="showorder" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lastChangdate" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="canceled" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "departmentid",
        "shortname",
        "fullname",
        "subcompanyid",
        "supdepartmentid",
        "showorder",
        "code",
        "action",
        "lastChangdate",
        "canceled"
    })
    public static class DepartmentBean {

        protected Integer departmentid;
        @XmlElement(required = true)
        protected String shortname;
        @XmlElement(required = true)
        protected String fullname;
        protected Integer subcompanyid;
        protected Integer supdepartmentid;
        protected Integer showorder;
        @XmlElement(required = true)
        protected String code;
        @XmlElement(required = true)
        protected String action;
        protected Integer lastChangdate;
        @XmlElement(required = true)
        protected String canceled;

        /**
         * Gets the value of the departmentid property.
         * 
         */
        public Integer getDepartmentid() {
            return departmentid;
        }

        /**
         * Sets the value of the departmentid property.
         * 
         */
        public void setDepartmentid(Integer value) {
            this.departmentid = value;
        }

        /**
         * Gets the value of the shortname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShortname() {
            return shortname;
        }

        /**
         * Sets the value of the shortname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShortname(String value) {
            this.shortname = value;
        }

        /**
         * Gets the value of the fullname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFullname() {
            return fullname;
        }

        /**
         * Sets the value of the fullname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFullname(String value) {
            this.fullname = value;
        }

        /**
         * Gets the value of the subcompanyid property.
         * 
         */
        public Integer getSubcompanyid() {
            return subcompanyid;
        }

        /**
         * Sets the value of the subcompanyid property.
         * 
         */
        public void setSubcompanyid(Integer value) {
            this.subcompanyid = value;
        }

        /**
         * Gets the value of the supdepartmentid property.
         * 
         */
        public Integer getSupdepartmentid() {
            return supdepartmentid;
        }

        /**
         * Sets the value of the supdepartmentid property.
         * 
         */
        public void setSupdepartmentid(Integer value) {
            this.supdepartmentid = value;
        }

        /**
         * Gets the value of the showorder property.
         * 
         */
        public Integer getShoworder() {
            return showorder;
        }

        /**
         * Sets the value of the showorder property.
         * 
         */
        public void setShoworder(Integer value) {
            this.showorder = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the action property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAction() {
            return action;
        }

        /**
         * Sets the value of the action property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAction(String value) {
            this.action = value;
        }

        /**
         * Gets the value of the lastChangdate property.
         * 
         */
        public Integer getLastChangdate() {
            return lastChangdate;
        }

        /**
         * Sets the value of the lastChangdate property.
         * 
         */
        public void setLastChangdate(Integer value) {
            this.lastChangdate = value;
        }

        /**
         * Gets the value of the canceled property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCanceled() {
            return canceled;
        }

        /**
         * Sets the value of the canceled property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCanceled(String value) {
            this.canceled = value;
        }

    }

}
