//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.21 at 08:49:00 PM CST 
//


package weaver.hrm.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubCompanyBean" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="subcompanyid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fullname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="supsubcompanyid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="website" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="showorder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="canceled" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lastChangdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subCompanyBean"
})
@XmlRootElement(name = "SubCompanyBean-array")
public class SubCompanyBeanArray {

    @XmlElement(name = "SubCompanyBean")
    protected List<SubCompanyBeanArray.SubCompanyBean> subCompanyBean;

    /**
     * Gets the value of the subCompanyBean property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subCompanyBean property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubCompanyBean().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubCompanyBeanArray.SubCompanyBean }
     * 
     * 
     */
    public List<SubCompanyBeanArray.SubCompanyBean> getSubCompanyBean() {
        if (subCompanyBean == null) {
            subCompanyBean = new ArrayList<SubCompanyBeanArray.SubCompanyBean>();
        }
        return this.subCompanyBean;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="subcompanyid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fullname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="supsubcompanyid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="website" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="showorder" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="canceled" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lastChangdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "subcompanyid",
        "shortname",
        "fullname",
        "supsubcompanyid",
        "website",
        "showorder",
        "code",
        "canceled",
        "action",
        "lastChangdate"
    })
    public static class SubCompanyBean {

        protected Integer subcompanyid;
        @XmlElement(required = true)
        protected String shortname;
        @XmlElement(required = true)
        protected String fullname;
        protected Integer supsubcompanyid;
        @XmlElement(required = true)
        protected String website;
        @XmlElement(required = true)
        protected String showorder;
        @XmlElement(required = true)
        protected String code;
        @XmlElement(required = true)
        protected String canceled;
        @XmlElement(required = true)
        protected String action;
        @XmlElement(required = true)
        protected String lastChangdate;

        /**
         * Gets the value of the subcompanyid property.
         * 
         */
        public Integer getSubcompanyid() {
            return subcompanyid;
        }

        /**
         * Sets the value of the subcompanyid property.
         * 
         */
        public void setSubcompanyid(Integer value) {
            this.subcompanyid = value;
        }

        /**
         * Gets the value of the shortname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShortname() {
            return shortname;
        }

        /**
         * Sets the value of the shortname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShortname(String value) {
            this.shortname = value;
        }

        /**
         * Gets the value of the fullname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFullname() {
            return fullname;
        }

        /**
         * Sets the value of the fullname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFullname(String value) {
            this.fullname = value;
        }

        /**
         * Gets the value of the supsubcompanyid property.
         * 
         */
        public Integer getSupsubcompanyid() {
            return supsubcompanyid;
        }

        /**
         * Sets the value of the supsubcompanyid property.
         * 
         */
        public void setSupsubcompanyid(Integer value) {
            this.supsubcompanyid = value;
        }

        /**
         * Gets the value of the website property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWebsite() {
            return website;
        }

        /**
         * Sets the value of the website property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWebsite(String value) {
            this.website = value;
        }

        /**
         * Gets the value of the showorder property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShoworder() {
            return showorder;
        }

        /**
         * Sets the value of the showorder property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShoworder(String value) {
            this.showorder = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the canceled property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCanceled() {
            return canceled;
        }

        /**
         * Sets the value of the canceled property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCanceled(String value) {
            this.canceled = value;
        }

        /**
         * Gets the value of the action property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAction() {
            return action;
        }

        /**
         * Sets the value of the action property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAction(String value) {
            this.action = value;
        }

        /**
         * Gets the value of the lastChangdate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastChangdate() {
            return lastChangdate;
        }

        /**
         * Sets the value of the lastChangdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastChangdate(String value) {
            this.lastChangdate = value;
        }

    }

}
