//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.21 at 09:05:14 PM CST 
//


package weaver.hrm.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UserBean" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="userid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="subcompanyid1" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="departmentid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="subcompanyname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="departmentname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="workcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="loginid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="seclevel" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="sex" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="jobtitle" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="jobcall" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="joblevel" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="jobactivitydesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="managerid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="assistantid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="locationid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="workroom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="mobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="mobilecall" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="systemlanguage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="birthday" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="folk" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="nativeplace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="regresidentplace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="certificatenum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="maritalstatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="policy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="bememberdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="bepartydate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="islabouunion" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="educationlevel" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="degree" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="healthinfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="residentplace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="homeaddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tempresidentnumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="startdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="enddate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="createdate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="lastChangdate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="accounttype" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="dsporder" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userBean"
})
@XmlRootElement(name = "UserBean-array")
public class UserBeanArray {

    @XmlElement(name = "UserBean")
    protected List<UserBeanArray.UserBean> userBean;

    /**
     * Gets the value of the userBean property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userBean property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserBean().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserBeanArray.UserBean }
     * 
     * 
     */
    public List<UserBeanArray.UserBean> getUserBean() {
        if (userBean == null) {
            userBean = new ArrayList<UserBeanArray.UserBean>();
        }
        return this.userBean;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="userid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="subcompanyid1" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="departmentid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="subcompanyname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="departmentname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="workcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="loginid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="seclevel" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="sex" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="jobtitle" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="jobcall" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="joblevel" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="jobactivitydesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="managerid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="assistantid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="locationid" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="workroom" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="mobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="mobilecall" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="systemlanguage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="birthday" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="folk" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="nativeplace" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="regresidentplace" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="certificatenum" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="maritalstatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="policy" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="bememberdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="bepartydate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="islabouunion" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="educationlevel" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="degree" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="healthinfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="residentplace" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="homeaddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tempresidentnumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="startdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="enddate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="createdate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="lastChangdate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="accounttype" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="dsporder" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userid",
        "subcompanyid1",
        "departmentid",
        "subcompanyname",
        "departmentname",
        "workcode",
        "lastname",
        "loginid",
        "password",
        "seclevel",
        "sex",
        "jobtitle",
        "jobcall",
        "joblevel",
        "jobactivitydesc",
        "managerid",
        "assistantid",
        "status",
        "locationid",
        "workroom",
        "telephone",
        "mobile",
        "mobilecall",
        "fax",
        "email",
        "systemlanguage",
        "birthday",
        "folk",
        "nativeplace",
        "regresidentplace",
        "certificatenum",
        "maritalstatus",
        "policy",
        "bememberdate",
        "bepartydate",
        "islabouunion",
        "educationlevel",
        "degree",
        "healthinfo",
        "height",
        "weight",
        "residentplace",
        "homeaddress",
        "tempresidentnumber",
        "startdate",
        "enddate",
        "createdate",
        "lastChangdate",
        "accounttype",
        "dsporder"
    })
    public static class UserBean {

        protected Integer userid;
        protected Integer subcompanyid1;
        protected Integer departmentid;
        @XmlElement(required = true)
        protected String subcompanyname;
        @XmlElement(required = true)
        protected String departmentname;
        @XmlElement(required = true)
        protected String workcode;
        @XmlElement(required = true)
        protected String lastname;
        @XmlElement(required = true)
        protected String loginid;
        @XmlElement(required = true)
        protected String password;
        protected Integer seclevel;
        @XmlElement(required = true)
        protected String sex;
        protected Integer jobtitle;
        protected Integer jobcall;
        protected Integer joblevel;
        @XmlElement(required = true)
        protected String jobactivitydesc;
        protected Integer managerid;
        protected Integer assistantid;
        protected Integer status;
        protected Integer locationid;
        @XmlElement(required = true)
        protected String workroom;
        @XmlElement(required = true)
        protected String telephone;
        @XmlElement(required = true)
        protected String mobile;
        @XmlElement(required = true)
        protected String mobilecall;
        @XmlElement(required = true)
        protected String fax;
        @XmlElement(required = true)
        protected String email;
        @XmlElement(required = true)
        protected String systemlanguage;
        @XmlElement(required = true)
        protected String birthday;
        @XmlElement(required = true)
        protected String folk;
        @XmlElement(required = true)
        protected String nativeplace;
        @XmlElement(required = true)
        protected String regresidentplace;
        @XmlElement(required = true)
        protected String certificatenum;
        @XmlElement(required = true)
        protected String maritalstatus;
        @XmlElement(required = true)
        protected String policy;
        @XmlElement(required = true)
        protected String bememberdate;
        @XmlElement(required = true)
        protected String bepartydate;
        protected Integer islabouunion;
        protected Integer educationlevel;
        @XmlElement(required = true)
        protected String degree;
        @XmlElement(required = true)
        protected String healthinfo;
        @XmlElement(required = true)
        protected String height;
        @XmlElement(required = true)
        protected String weight;
        @XmlElement(required = true)
        protected String residentplace;
        @XmlElement(required = true)
        protected String homeaddress;
        @XmlElement(required = true)
        protected String tempresidentnumber;
        @XmlElement(required = true)
        protected String startdate;
        @XmlElement(required = true)
        protected String enddate;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar createdate;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar lastChangdate;
        protected Integer accounttype;
        protected Integer dsporder;

        /**
         * Gets the value of the userid property.
         * 
         */
        public Integer getUserid() {
            return userid;
        }

        /**
         * Sets the value of the userid property.
         * 
         */
        public void setUserid(Integer value) {
            this.userid = value;
        }

        /**
         * Gets the value of the subcompanyid1 property.
         * 
         */
        public Integer getSubcompanyid1() {
            return subcompanyid1;
        }

        /**
         * Sets the value of the subcompanyid1 property.
         * 
         */
        public void setSubcompanyid1(Integer value) {
            this.subcompanyid1 = value;
        }

        /**
         * Gets the value of the departmentid property.
         * 
         */
        public Integer getDepartmentid() {
            return departmentid;
        }

        /**
         * Sets the value of the departmentid property.
         * 
         */
        public void setDepartmentid(Integer value) {
            this.departmentid = value;
        }

        /**
         * Gets the value of the subcompanyname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubcompanyname() {
            return subcompanyname;
        }

        /**
         * Sets the value of the subcompanyname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubcompanyname(String value) {
            this.subcompanyname = value;
        }

        /**
         * Gets the value of the departmentname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDepartmentname() {
            return departmentname;
        }

        /**
         * Sets the value of the departmentname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDepartmentname(String value) {
            this.departmentname = value;
        }

        /**
         * Gets the value of the workcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWorkcode() {
            return workcode;
        }

        /**
         * Sets the value of the workcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWorkcode(String value) {
            this.workcode = value;
        }

        /**
         * Gets the value of the lastname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastname() {
            return lastname;
        }

        /**
         * Sets the value of the lastname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastname(String value) {
            this.lastname = value;
        }

        /**
         * Gets the value of the loginid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLoginid() {
            return loginid;
        }

        /**
         * Sets the value of the loginid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLoginid(String value) {
            this.loginid = value;
        }

        /**
         * Gets the value of the password property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPassword() {
            return password;
        }

        /**
         * Sets the value of the password property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPassword(String value) {
            this.password = value;
        }

        /**
         * Gets the value of the seclevel property.
         * 
         */
        public Integer getSeclevel() {
            return seclevel;
        }

        /**
         * Sets the value of the seclevel property.
         * 
         */
        public void setSeclevel(Integer value) {
            this.seclevel = value;
        }

        /**
         * Gets the value of the sex property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSex() {
            return sex;
        }

        /**
         * Sets the value of the sex property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSex(String value) {
            this.sex = value;
        }

        /**
         * Gets the value of the jobtitle property.
         * 
         */
        public Integer getJobtitle() {
            return jobtitle;
        }

        /**
         * Sets the value of the jobtitle property.
         * 
         */
        public void setJobtitle(Integer value) {
            this.jobtitle = value;
        }

        /**
         * Gets the value of the jobcall property.
         * 
         */
        public Integer getJobcall() {
            return jobcall;
        }

        /**
         * Sets the value of the jobcall property.
         * 
         */
        public void setJobcall(Integer value) {
            this.jobcall = value;
        }

        /**
         * Gets the value of the joblevel property.
         * 
         */
        public Integer getJoblevel() {
            return joblevel;
        }

        /**
         * Sets the value of the joblevel property.
         * 
         */
        public void setJoblevel(Integer value) {
            this.joblevel = value;
        }

        /**
         * Gets the value of the jobactivitydesc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJobactivitydesc() {
            return jobactivitydesc;
        }

        /**
         * Sets the value of the jobactivitydesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJobactivitydesc(String value) {
            this.jobactivitydesc = value;
        }

        /**
         * Gets the value of the managerid property.
         * 
         */
        public Integer getManagerid() {
            return managerid;
        }

        /**
         * Sets the value of the managerid property.
         * 
         */
        public void setManagerid(Integer value) {
            this.managerid = value;
        }

        /**
         * Gets the value of the assistantid property.
         * 
         */
        public Integer getAssistantid() {
            return assistantid;
        }

        /**
         * Sets the value of the assistantid property.
         * 
         */
        public void setAssistantid(Integer value) {
            this.assistantid = value;
        }

        /**
         * Gets the value of the status property.
         * 
         */
        public Integer getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         */
        public void setStatus(Integer value) {
            this.status = value;
        }

        /**
         * Gets the value of the locationid property.
         * 
         */
        public Integer getLocationid() {
            return locationid;
        }

        /**
         * Sets the value of the locationid property.
         * 
         */
        public void setLocationid(Integer value) {
            this.locationid = value;
        }

        /**
         * Gets the value of the workroom property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWorkroom() {
            return workroom;
        }

        /**
         * Sets the value of the workroom property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWorkroom(String value) {
            this.workroom = value;
        }

        /**
         * Gets the value of the telephone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTelephone() {
            return telephone;
        }

        /**
         * Sets the value of the telephone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTelephone(String value) {
            this.telephone = value;
        }

        /**
         * Gets the value of the mobile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMobile() {
            return mobile;
        }

        /**
         * Sets the value of the mobile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMobile(String value) {
            this.mobile = value;
        }

        /**
         * Gets the value of the mobilecall property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMobilecall() {
            return mobilecall;
        }

        /**
         * Sets the value of the mobilecall property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMobilecall(String value) {
            this.mobilecall = value;
        }

        /**
         * Gets the value of the fax property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFax() {
            return fax;
        }

        /**
         * Sets the value of the fax property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFax(String value) {
            this.fax = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmail(String value) {
            this.email = value;
        }

        /**
         * Gets the value of the systemlanguage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSystemlanguage() {
            return systemlanguage;
        }

        /**
         * Sets the value of the systemlanguage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSystemlanguage(String value) {
            this.systemlanguage = value;
        }

        /**
         * Gets the value of the birthday property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBirthday() {
            return birthday;
        }

        /**
         * Sets the value of the birthday property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBirthday(String value) {
            this.birthday = value;
        }

        /**
         * Gets the value of the folk property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFolk() {
            return folk;
        }

        /**
         * Sets the value of the folk property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFolk(String value) {
            this.folk = value;
        }

        /**
         * Gets the value of the nativeplace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNativeplace() {
            return nativeplace;
        }

        /**
         * Sets the value of the nativeplace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNativeplace(String value) {
            this.nativeplace = value;
        }

        /**
         * Gets the value of the regresidentplace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegresidentplace() {
            return regresidentplace;
        }

        /**
         * Sets the value of the regresidentplace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegresidentplace(String value) {
            this.regresidentplace = value;
        }

        /**
         * Gets the value of the certificatenum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCertificatenum() {
            return certificatenum;
        }

        /**
         * Sets the value of the certificatenum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCertificatenum(String value) {
            this.certificatenum = value;
        }

        /**
         * Gets the value of the maritalstatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaritalstatus() {
            return maritalstatus;
        }

        /**
         * Sets the value of the maritalstatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaritalstatus(String value) {
            this.maritalstatus = value;
        }

        /**
         * Gets the value of the policy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPolicy() {
            return policy;
        }

        /**
         * Sets the value of the policy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPolicy(String value) {
            this.policy = value;
        }

        /**
         * Gets the value of the bememberdate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBememberdate() {
            return bememberdate;
        }

        /**
         * Sets the value of the bememberdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBememberdate(String value) {
            this.bememberdate = value;
        }

        /**
         * Gets the value of the bepartydate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBepartydate() {
            return bepartydate;
        }

        /**
         * Sets the value of the bepartydate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBepartydate(String value) {
            this.bepartydate = value;
        }

        /**
         * Gets the value of the islabouunion property.
         * 
         */
        public Integer getIslabouunion() {
            return islabouunion;
        }

        /**
         * Sets the value of the islabouunion property.
         * 
         */
        public void setIslabouunion(Integer value) {
            this.islabouunion = value;
        }

        /**
         * Gets the value of the educationlevel property.
         * 
         */
        public Integer getEducationlevel() {
            return educationlevel;
        }

        /**
         * Sets the value of the educationlevel property.
         * 
         */
        public void setEducationlevel(Integer value) {
            this.educationlevel = value;
        }

        /**
         * Gets the value of the degree property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDegree() {
            return degree;
        }

        /**
         * Sets the value of the degree property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDegree(String value) {
            this.degree = value;
        }

        /**
         * Gets the value of the healthinfo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHealthinfo() {
            return healthinfo;
        }

        /**
         * Sets the value of the healthinfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHealthinfo(String value) {
            this.healthinfo = value;
        }

        /**
         * Gets the value of the height property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHeight() {
            return height;
        }

        /**
         * Sets the value of the height property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHeight(String value) {
            this.height = value;
        }

        /**
         * Gets the value of the weight property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWeight() {
            return weight;
        }

        /**
         * Sets the value of the weight property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWeight(String value) {
            this.weight = value;
        }

        /**
         * Gets the value of the residentplace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResidentplace() {
            return residentplace;
        }

        /**
         * Sets the value of the residentplace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResidentplace(String value) {
            this.residentplace = value;
        }

        /**
         * Gets the value of the homeaddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeaddress() {
            return homeaddress;
        }

        /**
         * Sets the value of the homeaddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeaddress(String value) {
            this.homeaddress = value;
        }

        /**
         * Gets the value of the tempresidentnumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTempresidentnumber() {
            return tempresidentnumber;
        }

        /**
         * Sets the value of the tempresidentnumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTempresidentnumber(String value) {
            this.tempresidentnumber = value;
        }

        /**
         * Gets the value of the startdate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStartdate() {
            return startdate;
        }

        /**
         * Sets the value of the startdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStartdate(String value) {
            this.startdate = value;
        }

        /**
         * Gets the value of the enddate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEnddate() {
            return enddate;
        }

        /**
         * Sets the value of the enddate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEnddate(String value) {
            this.enddate = value;
        }

        /**
         * Gets the value of the createdate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCreatedate() {
            return createdate;
        }

        /**
         * Sets the value of the createdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCreatedate(XMLGregorianCalendar value) {
            this.createdate = value;
        }

        /**
         * Gets the value of the lastChangdate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getLastChangdate() {
            return lastChangdate;
        }

        /**
         * Sets the value of the lastChangdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setLastChangdate(XMLGregorianCalendar value) {
            this.lastChangdate = value;
        }

        /**
         * Gets the value of the accounttype property.
         * 
         */
        public Integer getAccounttype() {
            return accounttype;
        }

        /**
         * Sets the value of the accounttype property.
         * 
         */
        public void setAccounttype(Integer value) {
            this.accounttype = value;
        }

        /**
         * Gets the value of the dsporder property.
         * 
         */
        public Integer getDsporder() {
            return dsporder;
        }

        /**
         * Sets the value of the dsporder property.
         * 
         */
        public void setDsporder(Integer value) {
            this.dsporder = value;
        }

    }

}
