
package cn.com.hwxt.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GdDataWs", targetNamespace = "http://service.hwxt.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GdDataWs {


    /**
     * 
     * @param xmlName
     * @param gdrCode
     * @param dataJson
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dataReciveJson", targetNamespace = "http://service.hwxt.com.cn/", className = "cn.com.hwxt.service.DataReciveJson")
    @ResponseWrapper(localName = "dataReciveJsonResponse", targetNamespace = "http://service.hwxt.com.cn/", className = "cn.com.hwxt.service.DataReciveJsonResponse")
    public String dataReciveJson(
        @WebParam(name = "xmlName", targetNamespace = "")
        String xmlName,
        @WebParam(name = "dataJson", targetNamespace = "")
        String dataJson,
        @WebParam(name = "gdrCode", targetNamespace = "")
        String gdrCode);

    /**
     * 
     * @param dataXml
     * @param xmlName
     * @param gdrCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dataReciveXml", targetNamespace = "http://service.hwxt.com.cn/", className = "cn.com.hwxt.service.DataReciveXml")
    @ResponseWrapper(localName = "dataReciveXmlResponse", targetNamespace = "http://service.hwxt.com.cn/", className = "cn.com.hwxt.service.DataReciveXmlResponse")
    public String dataReciveXml(
        @WebParam(name = "xmlName", targetNamespace = "")
        String xmlName,
        @WebParam(name = "dataXml", targetNamespace = "")
        String dataXml,
        @WebParam(name = "gdrCode", targetNamespace = "")
        String gdrCode);

    /**
     * 
     * @param dataXml
     * @param xmlName
     * @param gdrCode
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fileReciveXml", targetNamespace = "http://service.hwxt.com.cn/", className = "cn.com.hwxt.service.FileReciveXml")
    @ResponseWrapper(localName = "fileReciveXmlResponse", targetNamespace = "http://service.hwxt.com.cn/", className = "cn.com.hwxt.service.FileReciveXmlResponse")
    public Integer fileReciveXml(
        @WebParam(name = "xmlName", targetNamespace = "")
        String xmlName,
        @WebParam(name = "dataXml", targetNamespace = "")
        String dataXml,
        @WebParam(name = "gdrCode", targetNamespace = "")
        String gdrCode);

    /**
     * 
     * @param xmlName
     * @param gdrCode
     * @param dataJson
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fileReciveJson", targetNamespace = "http://service.hwxt.com.cn/", className = "cn.com.hwxt.service.FileReciveJson")
    @ResponseWrapper(localName = "fileReciveJsonResponse", targetNamespace = "http://service.hwxt.com.cn/", className = "cn.com.hwxt.service.FileReciveJsonResponse")
    public Integer fileReciveJson(
        @WebParam(name = "xmlName", targetNamespace = "")
        String xmlName,
        @WebParam(name = "dataJson", targetNamespace = "")
        String dataJson,
        @WebParam(name = "gdrCode", targetNamespace = "")
        String gdrCode);

}
