
package cn.com.hwxt.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GdServiceImplService", targetNamespace = "http://service.hwxt.com.cn/", wsdlLocation = "http://localhost:8887/HamsPort/cxf/GdDataWsSingle?wsdl")
public class GdServiceImplService
    extends Service
{

    private final static URL GDSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GDSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName GDSERVICEIMPLSERVICE_QNAME = new QName("http://service.hwxt.com.cn/", "GdServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8887/HamsPort/cxf/GdDataWsSingle?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GDSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        GDSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public GdServiceImplService() {
        super(__getWsdlLocation(), GDSERVICEIMPLSERVICE_QNAME);
    }

    public GdServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GDSERVICEIMPLSERVICE_QNAME, features);
    }

    public GdServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, GDSERVICEIMPLSERVICE_QNAME);
    }

    public GdServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GDSERVICEIMPLSERVICE_QNAME, features);
    }

    public GdServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GdServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GdDataWs
     */
    @WebEndpoint(name = "GdDataWsPort")
    public GdDataWs getGdDataWsPort() {
        return super.getPort(new QName("http://service.hwxt.com.cn/", "GdDataWsPort"), GdDataWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GdDataWs
     */
    @WebEndpoint(name = "GdDataWsPort")
    public GdDataWs getGdDataWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.hwxt.com.cn/", "GdDataWsPort"), GdDataWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GDSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw GDSERVICEIMPLSERVICE_EXCEPTION;
        }
        return GDSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
