
package weaver.todo.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OfsTodoDataWebService", targetNamespace = "webservices.ofs.weaver.com.cn", wsdlLocation = "http://183.64.63.155:83/services/OfsTodoDataWebService?wsdl")
public class OfsTodoDataWebService
    extends Service
{

    private final static URL OFSTODODATAWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException OFSTODODATAWEBSERVICE_EXCEPTION;
    private final static QName OFSTODODATAWEBSERVICE_QNAME = new QName("webservices.ofs.weaver.com.cn", "OfsTodoDataWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://183.64.63.155:83/services/OfsTodoDataWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OFSTODODATAWEBSERVICE_WSDL_LOCATION = url;
        OFSTODODATAWEBSERVICE_EXCEPTION = e;
    }

    public OfsTodoDataWebService() {
        super(__getWsdlLocation(), OFSTODODATAWEBSERVICE_QNAME);
    }

    public OfsTodoDataWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OFSTODODATAWEBSERVICE_QNAME, features);
    }

    public OfsTodoDataWebService(URL wsdlLocation) {
        super(wsdlLocation, OFSTODODATAWEBSERVICE_QNAME);
    }

    public OfsTodoDataWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OFSTODODATAWEBSERVICE_QNAME, features);
    }

    public OfsTodoDataWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OfsTodoDataWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OfsTodoDataWebServicePortType
     */
    @WebEndpoint(name = "OfsTodoDataWebServiceHttpPort")
    public OfsTodoDataWebServicePortType getOfsTodoDataWebServiceHttpPort() {
        return super.getPort(new QName("webservices.ofs.weaver.com.cn", "OfsTodoDataWebServiceHttpPort"), OfsTodoDataWebServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OfsTodoDataWebServicePortType
     */
    @WebEndpoint(name = "OfsTodoDataWebServiceHttpPort")
    public OfsTodoDataWebServicePortType getOfsTodoDataWebServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("webservices.ofs.weaver.com.cn", "OfsTodoDataWebServiceHttpPort"), OfsTodoDataWebServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OFSTODODATAWEBSERVICE_EXCEPTION!= null) {
            throw OFSTODODATAWEBSERVICE_EXCEPTION;
        }
        return OFSTODODATAWEBSERVICE_WSDL_LOCATION;
    }

}
