
package weaver.todo.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OfsTodoDataWebServicePortType", targetNamespace = "webservices.ofs.weaver.com.cn")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OfsTodoDataWebServicePortType {


    /**
     * 
     * @param in0
     * @return
     *     returns weaver.todo.webservice.AnyType2AnyTypeMap
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.ofs.weaver.com.cn")
    @RequestWrapper(localName = "processOverRequestByMap", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ProcessOverRequestByMap")
    @ResponseWrapper(localName = "processOverRequestByMapResponse", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ProcessOverRequestByMapResponse")
    public AnyType2AnyTypeMap processOverRequestByMap(
        @WebParam(name = "in0", targetNamespace = "webservices.ofs.weaver.com.cn")
        AnyType2AnyTypeMap in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.ofs.weaver.com.cn")
    @RequestWrapper(localName = "processOverRequestByJson", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ProcessOverRequestByJson")
    @ResponseWrapper(localName = "processOverRequestByJsonResponse", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ProcessOverRequestByJsonResponse")
    public String processOverRequestByJson(
        @WebParam(name = "in0", targetNamespace = "webservices.ofs.weaver.com.cn")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns weaver.todo.webservice.AnyType2AnyTypeMap
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.ofs.weaver.com.cn")
    @RequestWrapper(localName = "receiveRequestInfoByMap", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ReceiveRequestInfoByMap")
    @ResponseWrapper(localName = "receiveRequestInfoByMapResponse", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ReceiveRequestInfoByMapResponse")
    public AnyType2AnyTypeMap receiveRequestInfoByMap(
        @WebParam(name = "in0", targetNamespace = "webservices.ofs.weaver.com.cn")
        AnyType2AnyTypeMap in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.ofs.weaver.com.cn")
    @RequestWrapper(localName = "receiveRequestInfoByXml", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ReceiveRequestInfoByXml")
    @ResponseWrapper(localName = "receiveRequestInfoByXmlResponse", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ReceiveRequestInfoByXmlResponse")
    public String receiveRequestInfoByXml(
        @WebParam(name = "in0", targetNamespace = "webservices.ofs.weaver.com.cn")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.ofs.weaver.com.cn")
    @RequestWrapper(localName = "receiveTodoRequestByXml", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ReceiveTodoRequestByXml")
    @ResponseWrapper(localName = "receiveTodoRequestByXmlResponse", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ReceiveTodoRequestByXmlResponse")
    public String receiveTodoRequestByXml(
        @WebParam(name = "in0", targetNamespace = "webservices.ofs.weaver.com.cn")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.ofs.weaver.com.cn")
    @RequestWrapper(localName = "deleteRequestInfoByXML", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.DeleteRequestInfoByXML")
    @ResponseWrapper(localName = "deleteRequestInfoByXMLResponse", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.DeleteRequestInfoByXMLResponse")
    public String deleteRequestInfoByXML(
        @WebParam(name = "in0", targetNamespace = "webservices.ofs.weaver.com.cn")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns weaver.todo.webservice.AnyType2AnyTypeMap
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.ofs.weaver.com.cn")
    @RequestWrapper(localName = "receiveTodoRequestByMap", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ReceiveTodoRequestByMap")
    @ResponseWrapper(localName = "receiveTodoRequestByMapResponse", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ReceiveTodoRequestByMapResponse")
    public AnyType2AnyTypeMap receiveTodoRequestByMap(
        @WebParam(name = "in0", targetNamespace = "webservices.ofs.weaver.com.cn")
        AnyType2AnyTypeMap in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.ofs.weaver.com.cn")
    @RequestWrapper(localName = "deleteUserRequestInfoByJson", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.DeleteUserRequestInfoByJson")
    @ResponseWrapper(localName = "deleteUserRequestInfoByJsonResponse", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.DeleteUserRequestInfoByJsonResponse")
    public String deleteUserRequestInfoByJson(
        @WebParam(name = "in0", targetNamespace = "webservices.ofs.weaver.com.cn")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.ofs.weaver.com.cn")
    @RequestWrapper(localName = "processDoneRequestByJson", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ProcessDoneRequestByJson")
    @ResponseWrapper(localName = "processDoneRequestByJsonResponse", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ProcessDoneRequestByJsonResponse")
    public String processDoneRequestByJson(
        @WebParam(name = "in0", targetNamespace = "webservices.ofs.weaver.com.cn")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.ofs.weaver.com.cn")
    @RequestWrapper(localName = "processOverRequestByXml", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ProcessOverRequestByXml")
    @ResponseWrapper(localName = "processOverRequestByXmlResponse", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ProcessOverRequestByXmlResponse")
    public String processOverRequestByXml(
        @WebParam(name = "in0", targetNamespace = "webservices.ofs.weaver.com.cn")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.ofs.weaver.com.cn")
    @RequestWrapper(localName = "receiveRequestInfoByJson", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ReceiveRequestInfoByJson")
    @ResponseWrapper(localName = "receiveRequestInfoByJsonResponse", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ReceiveRequestInfoByJsonResponse")
    public String receiveRequestInfoByJson(
        @WebParam(name = "in0", targetNamespace = "webservices.ofs.weaver.com.cn")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.ofs.weaver.com.cn")
    @RequestWrapper(localName = "deleteRequestInfoByJson", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.DeleteRequestInfoByJson")
    @ResponseWrapper(localName = "deleteRequestInfoByJsonResponse", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.DeleteRequestInfoByJsonResponse")
    public String deleteRequestInfoByJson(
        @WebParam(name = "in0", targetNamespace = "webservices.ofs.weaver.com.cn")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns weaver.todo.webservice.AnyType2AnyTypeMap
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.ofs.weaver.com.cn")
    @RequestWrapper(localName = "deleteRequestInfoByMap", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.DeleteRequestInfoByMap")
    @ResponseWrapper(localName = "deleteRequestInfoByMapResponse", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.DeleteRequestInfoByMapResponse")
    public AnyType2AnyTypeMap deleteRequestInfoByMap(
        @WebParam(name = "in0", targetNamespace = "webservices.ofs.weaver.com.cn")
        AnyType2AnyTypeMap in0);

    /**
     * 
     * @param in0
     * @return
     *     returns weaver.todo.webservice.AnyType2AnyTypeMap
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.ofs.weaver.com.cn")
    @RequestWrapper(localName = "deleteUserRequestInfoByMap", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.DeleteUserRequestInfoByMap")
    @ResponseWrapper(localName = "deleteUserRequestInfoByMapResponse", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.DeleteUserRequestInfoByMapResponse")
    public AnyType2AnyTypeMap deleteUserRequestInfoByMap(
        @WebParam(name = "in0", targetNamespace = "webservices.ofs.weaver.com.cn")
        AnyType2AnyTypeMap in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.ofs.weaver.com.cn")
    @RequestWrapper(localName = "processDoneRequestByXml", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ProcessDoneRequestByXml")
    @ResponseWrapper(localName = "processDoneRequestByXmlResponse", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ProcessDoneRequestByXmlResponse")
    public String processDoneRequestByXml(
        @WebParam(name = "in0", targetNamespace = "webservices.ofs.weaver.com.cn")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.ofs.weaver.com.cn")
    @RequestWrapper(localName = "receiveTodoRequestByJson", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ReceiveTodoRequestByJson")
    @ResponseWrapper(localName = "receiveTodoRequestByJsonResponse", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ReceiveTodoRequestByJsonResponse")
    public String receiveTodoRequestByJson(
        @WebParam(name = "in0", targetNamespace = "webservices.ofs.weaver.com.cn")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns weaver.todo.webservice.AnyType2AnyTypeMap
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.ofs.weaver.com.cn")
    @RequestWrapper(localName = "processDoneRequestByMap", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ProcessDoneRequestByMap")
    @ResponseWrapper(localName = "processDoneRequestByMapResponse", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.ProcessDoneRequestByMapResponse")
    public AnyType2AnyTypeMap processDoneRequestByMap(
        @WebParam(name = "in0", targetNamespace = "webservices.ofs.weaver.com.cn")
        AnyType2AnyTypeMap in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.ofs.weaver.com.cn")
    @RequestWrapper(localName = "deleteUserRequestInfoByXML", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.DeleteUserRequestInfoByXML")
    @ResponseWrapper(localName = "deleteUserRequestInfoByXMLResponse", targetNamespace = "webservices.ofs.weaver.com.cn", className = "weaver.todo.webservice.DeleteUserRequestInfoByXMLResponse")
    public String deleteUserRequestInfoByXML(
        @WebParam(name = "in0", targetNamespace = "webservices.ofs.weaver.com.cn")
        String in0);

}
